language: node_js
node_js:
  - stable
install:
  - npm install
services:
  - mongodb
cache:
  directories:
  - node_modules
  - client/node_modules
before_script:
  - npm install
script: 
  - npm test